steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=${_APP_NAME}']
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', '${_APP_NAME}_$COMMIT_SHA', '${_APP_NAME}']
    env: ['PROJECT_ROOT=${_APP_NAME}']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test']
    env: ['PROJECT_ROOT=${_APP_NAME}']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'BINARY=${_APP_NAME}_$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA',
       '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/bash'
    args: ['docker-tags.bash']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'APP_NAME=$_APP_NAME'
      - 'PROJECT_ID=$PROJECT_ID'
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}'
    paths: ['${_APP_NAME}_$COMMIT_SHA']
substitutions:
  _APP_NAME: pro.payload.api
  _ARTIFACT_BUCKET: artifact-storage
