version: '3'
services:
  api:
    build: .
    ports:
      - "8081:8081"
    links:
      - mongo
    networks:
      - proxy
    depends_on:
      - mongo
  mongo:
    image: mongo:4.1-xenial
    networks:
      - proxy
    ports:
      - "27018:27017"
networks:
  proxy:
    driver: bridge
